### ISSUE TITLE
Organization Teams

### ISSUE THREAD

**Issue by dbrgn** [SwissPy/sps17#4]
_(Moved from SwissPy/swisspycon#75)_

For the next edition we should probably create "mini-teams" with people responsible for a specific part from beginning to the end. I'll create a separate issue for that. Examples could be:
- [x] **General communications** (sending out e-mails to attendees, managing newsletters, etc) @href
- [x] **Speaker communications & coordination** (make sure the Speakers have all information they need (#13), make sure they are welcomed on-site, and coordinate the talk managers during the day) @bkarolina
- [x] **On-site social media communication** (filling the Twitter account with updates (#20)): @The-Compiler 
- [ ] ~~**Day program** (be responsible for the schedule and the talk selection, lead the meetings that are held to decide which talks are accepted)~~
- [ ] **Catering** (coffee, food, drinks, social events... (#19))
- [x] **Technical infrastructure** (live audio, projector, audio recording, video recording, lights, room infrastructure, video adapters... (#28)): @dbrgn
- [x] **Registration before event** (handle the sign-up of attendees (#14)) @andrekeller
- [x] **Finances** (create a budget (#9), make sure the entry fee can cover costs): @chiesax 
- [x] **Sponsoring** (Do we want sponsors? If yes, what packages do we offer? Make sure we have good communication with the sponsors. (#16)): @href
- [ ] **Website** (manage the website (#21)):
- [x] **PR** (posters, design, reports, photos (#12)): @href, @bkarolina 
- [x] **Location** (organizing rooms, break area etc): @dbrgn
- [ ] **Helpers** (acquire helpers, manage helpers)

Note that this is just about responsibility. I think the whole process should still be democratic, and you can look for other people that help you in your area.

Any other teams that I missed?

**Comment by dbrgn** [comment]
I'd opt for taking over the "Technical infrastructure" part. I'll be able to borrow the same PA system as last time.

How do we distribute the rest? I assume @chiesax will take over finances?

**Comment by chiesax** [comment]
Yes, and we need people for sponsoring...

**Comment by href** [comment]
I think it makes sense to start breaking up all these jobs into small tasks (i.e. issues) and then people can self assign. We can keep the jobs together by tagging them with the organisation laid out in this issue.

Also, the more descriptive and concrete the issue, the better.

**Comment by andrekeller** [comment]
I agree, at least for me this is all a bit overwhelming at the moment :-)

**Comment by dbrgn** [comment]
I still think that - even while breaking up jobs into smaller tasks, which is a good idea - we need a responsible person to keep the overview.

I can also take over responsibility for location.

Note to the "newcomers": Even if you didn't do something like that before, just pick a job that interests you. We'll assist you however we can!

**Comment by href** [comment]
I added myself to general communications, that _is_ the secretary's job.

**Comment by href** [comment]
I'm removing the day-program responsibility. I don't really see how this is a separate job. The talks are being voted on and the schedule is going to be decided afterwards by the same set of people.

**Comment by href** [comment]
I'm also not sure about the sponsoring, I think this should be done by @ccdesales and me, since you'd want someone official to handle this (esp. since we might need to sign contracts).
